code --install-extension alefragnani.project-manager
code --install-extension Angular.ng-template
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.winteriscoming
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension naumovs.color-highlight
code --install-extension naumovs.theme-oceanicnext
code --install-extension onecentlin.laravel-blade
code --install-extension PKief.material-icon-theme
code --install-extension robinbentley.sass-indented
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wesbos.theme-cobalt2
code --install-extension zhuangtongfa.Material-theme
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.project-manager
code --install-extension Angular.ng-template
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.jquerysnippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension humao.rest-client
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.winteriscoming
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension naumovs.color-highlight
code --install-extension naumovs.theme-oceanicnext
code --install-extension nrwl.angular-console
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension robinbentley.sass-indented
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wesbos.theme-cobalt2
code --install-extension zhuangtongfa.Material-theme
